name: decision-helper backend

on:
  push:
    branches:
    - 'master'

env:
  CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  PROJECT_ID: ${{ secrets.GOOGLE_PROJECT }}
  GKE_CLUSTER: decision-helper-clusters
  LOCATION: asia-southeast2
  IMAGE_REPOSITORY: decision-helper-repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: authenticate to google cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ env.CREDENTIALS }}
        project_id: ${{ env.PROJECT_ID }}

    - name: set up cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: create repository
      run: |
        gcloud artifacts repositories create ${{ env.IMAGE_REPOSITORY }} \
        --repository-format=docker \
        --location=${{ env.LOCATION }} 

    - name: build and push the docker image
      run: |
        gcloud auth configure-docker ${{ env.LOCATION }}-docker.pkg.dev
        docker build -t ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_REPOSITORY }}/be:latest .
        docker push ${{ env.LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.IMAGE_REPOSITORY }}/be:latest
  
    - name: set up GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.LOCATION }}
